import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
    en: {
        // Navbar
        adminDashboard: 'Admin Dashboard',
        courses: 'Courses',
        stock: 'Stock',
        logout: 'Logout',

        // Login Page
        welcomeBack: 'Welcome Back',
        signInToAccount: 'Sign in to your KMT Trade account',
        emailAddress: 'Email Address',
        password: 'Password',
        secureLogin: 'Secure Login',
        authenticating: 'Authenticating...',
        dontHaveAccount: "Don't have an account?",
        signUp: 'Sign Up',
        secureTrading: 'Secure Trading Platform',
        copyright: '© 2026 KMT Trade. All rights reserved.',

        // Signup Page
        createAccount: 'Create Account',
        joinKMT: 'Join KMT Trade and start your trading journey',
        fullName: 'Full Name',
        confirmPassword: 'Confirm Password',
        creatingAccount: 'Creating Account...',
        alreadyHaveAccount: 'Already have an account?',
        signIn: 'Sign In',

        // Landing Page
        professionalTrading: 'Professional Trading Education - KMT Trade',
        masterMarkets: 'Master the Markets',
        withConfidence: 'With Confidence',
        tradingDescription: 'Professional trading education designed for serious investors. Unlock premium strategies, live analysis, and expert mentorship.',
        startLearning: 'Start Learning Now',
        viewCourses: 'View Course Catalog',
        students: 'Students',
        certifiedMentors: 'Certified Mentors',

        // Courses Page
        tradingCourses: 'Courses & Learning Paths',
        courseDescription: 'Browse Trading Platform, News Courses, Paid Programs, and Praxis & Training — all organized in one place.',
        lessons: 'Lessons',
        waitlist: 'Waitlist',
        startCourse: 'Start Course',
        continueCourse: 'Continue Course',
        completed: 'COMPLETED',

        // Video Player
        premiumContent: 'Premium Content',
        premiumDescription: 'This masterclass lesson is reserved for our premium members. Unlock full access to elevate your trading game.',
        subscribeToUnlock: 'Subscribe to Unlock',
        courseContent: 'Course Content',

        // Admin Dashboard
        adminDashboardTitle: 'Admin Dashboard',

        // Stock Journal
        tradingDashboard: 'Trading Dashboard',
        stockJournal: 'Stock Journal',
        startingCapital: 'Starting Capital',
        currentCapital: 'Current Capital',
        totalProfitLoss: 'Total Profit/Loss',
        logNewTrade: 'Log New Trade',
        enterTradeDetails: 'Enter your trade details below',
        date: 'Date',
        assetName: 'Asset Name',
        tradeType: 'Trade Type',
        buyLong: 'Buy / Long',
        sellShort: 'Sell / Short',
        quantity: 'Quantity',
        entryPrice: 'Entry Price',
        exitPrice: 'Exit Price',
        strategyTag: 'Strategy Tag',
        tradeNotes: 'Trade Notes',
        addTradeEntry: 'Add Trade Entry',
        filters: 'Filters',
        exportData: 'Export Data',
        totalTrades: 'Total Trades',
        winRate: 'Win Rate',
        bestTrade: 'Best Trade',
        worstTrade: 'Worst Trade',
        avgMonthlyReturn: 'Avg Monthly Return',
        equityGrowth: 'Equity Growth',
        cumulativePerformance: 'Cumulative performance over time',
        monthlyPerformance: 'Monthly Performance',
        profitLossPerMonth: 'Profit & Loss percentage per month',
        tradeHistory: 'Trade History',
        noTradesLogged: 'No trades logged yet. Start adding your first trade entry.',
        assetLabel: 'Date / Asset',
        typeLabel: 'Type',
        entryExitLabel: 'Entry / Exit',
        qtyLabel: 'Qty',
        profitLossLabel: 'Profit / Loss',
        strategyLabel: 'Strategy',
        actionsLabel: 'Actions',
        confirmDelete: 'Delete trade?',
        journal: 'Journal',
        confidence: 'Confidence',
        uploadScreenshots: 'Upload Screenshots',
        chooseFile: 'Choose File',
        noFileChosen: 'No file chosen',
        clickToUpload: 'Click to upload or drag and drop',
        imageNote: 'PNG, JPG or WEBP (Max. 2MB)',
        totalUsers: 'Total Users',
        premiumMembers: 'Premium Members',
        totalContent: 'Total Content',
        revenue: 'Revenue (Est)',
        userManagement: 'User Management',
        manageAccess: 'Manage access rights',
        user: 'User',
        email: 'Email',
        role: 'Role',
        status: 'Status',
        actions: 'Actions',
        admin: 'Admin',
        normal: 'Normal',
        premium: 'Premium',
        activatePremium: 'Activate Premium',
        deactivatePremium: 'Deactivate Premium',
        quickAccess: 'Quick Access',
        usersDesc: 'Manage users, roles, and subscriptions',
        coursesDesc: 'Manage course content and visibility',
        uploadDesc: 'Upload new video lessons',
        newsDesc: 'Publish news and announcements',
        settingsDesc: 'Configure platform settings',
        stockJournalDesc: 'Personal trading journal and performance analytics',
        goToPage: 'Go to Page',

        // Dashboard Stats & Charts
        overview: 'System Overview',
        userDistribution: 'User Distribution',
        revenueTrends: 'Revenue Trends',
        contentPerformance: 'Content Performance',
        premiumUsers: 'Premium Users',
        freeUsers: 'Free Users',
        admins: 'Admins',
        monthlyGrowth: 'Monthly Growth',
        last30Days: 'Last 30 Days',
        totalViews: 'Total Views',
        engagement: 'Engagement',

        // Admin Sidebar
        courseManagement: 'Course Management',
        usersManagement: 'Users',
        profile: 'Profile',

        // Course Management
        addNewCourse: 'Add New Course',
        courseTitle: 'Course Title',
        adminCourseDescription: 'Course Description',
        courseThumbnail: 'Thumbnail URL',
        courseLevel: 'Course Level',
        courseType: 'Course Type',
        public: 'Public',
        premiumOnly: 'Premium Only',
        beginner: 'Beginner',
        intermediate: 'Intermediate',
        professional: 'Professional',
        yourCurrentLevel: 'Your Current Level',
        levelProgress: 'Level Progress',
        levelCompleteDesc: 'Level Complete! Next level unlocked.',
        completeVideosToUnlock: 'Complete all videos to unlock next level.',
        uploadCourse: 'Upload Course',
        editCourse: 'Edit Course',
        deleteCourse: 'Delete Course',
        hideCourse: 'Hide Course',
        showCourse: 'Show Course',
        courseStats: 'Course Statistics',
        premiumViews: 'Premium Views',
        cancel: 'Cancel',
        save: 'Save',
        delete: 'Delete',
        confirm: 'Confirm',
        edit: 'Edit',

        // User Management
        searchUsers: 'Search users...',
        filterByStatus: 'Filter by status',
        allUsers: 'All Users',
        activeUsers: 'Active Users',
        inactiveUsers: 'Inactive Users',
        userId: 'User ID',
        accountStatus: 'Account Status',
        subscriptionStatus: 'Subscription',
        active: 'Active',
        inactive: 'Inactive',
        activateAccount: 'Activate Account',
        deactivateAccount: 'Deactivate Account',
        deleteAccount: 'Delete Account',
        deleteUserConfirm: 'Are you sure you want to delete this user?',
        deleteUserWarning: 'This action cannot be undone.',

        // Admin Profile
        adminProfile: 'Admin Profile',
        profileImage: 'Profile Image',
        changeImage: 'Change Image',
        adminName: 'Name',
        adminEmail: 'Email',
        editProfile: 'Edit Profile',
        saveChanges: 'Save Changes',
        profileUpdated: 'Profile updated successfully',

        // Messages
        courseAdded: 'Course added successfully',
        courseUpdated: 'Course updated successfully',
        courseDeleted: 'Course deleted successfully',
        userDeleted: 'User deleted successfully',
        userActivated: 'User activated successfully',
        userDeactivated: 'User deactivated successfully',
        settings: 'Settings',

        // Upload Course Page
        uploadCoursePageTitle: 'Upload Course Video',
        courseDetails: 'Course Details',
        videoDetails: 'Video Details',
        accessSettings: 'Access Settings',
        videoTitle: 'Video Title',
        videoDescription: 'Video Description',
        dragDropVideo: 'Drag & Drop video here',
        orBrowse: 'or browse to upload',
        videoDuration: 'Duration (mm:ss)',
        videoType: 'Video Type',
        free: 'Free',
        uploading: 'Uploading...',
        uploadSuccess: 'Video uploaded successfully!',
        uploadError: 'Error uploading video',
        selectThumbnail: 'Select Thumbnail',
        thumbnailPreview: 'Thumbnail Preview',
        fileSelected: 'File selected:',
        removeFile: 'Remove',

        // Users Page Translates
        manageUsersDesc: 'Manage platform users and subscriptions',
        joined: 'Joined',
        noUsersFound: 'No users found matching',
        removePremium: 'Remove Premium',
        makePremium: 'Make Premium',
        freePlan: 'Free Plan',
        premiumPlan: 'Premium',
        learningLevel: 'Learning Level',
        progress: 'Progress',

        // Courses Settings Page Translates
        coursesSettingsTitle: 'Courses Settings',
        manageCoursesDesc: 'Manage and organize your course content',
        noImage: 'No Image',
        startUploading: 'No courses available. Start by uploading one.',
        published: 'Published',
        hidden: 'Hidden',
        deleteCourseConfirm: 'Are you sure you want to delete this course?',

        // Settings Page Translates
        platformSettings: 'Platform Settings',
        general: 'General',
        platformName: 'Platform Name',
        platformNameDesc: 'This name will appear in the page title and emails.',
        themePreference: 'Theme Preference',
        current: 'Current',
        switchTheme: 'Switch Theme',
        systemLanguage: 'System Language',
        switchLanguage: 'Switch Language',
        accessControl: 'Access Control',
        adminOnly: 'Admin Only',
        maintenanceMode: 'Maintenance Mode',
        maintenanceModeDesc: 'Disable access for all non-admin users',
        allowSignups: 'Allow New Signups',
        allowSignupsDesc: 'Enable or disable new user registration',
        lightMode: 'Light Mode',
        darkMode: 'Dark Mode',
        english: 'English',
        arabic: 'Arabic',

        // News Page Translates
        news: 'News',
        newsManagementDescription: 'News Management',
        newsManagementDesc: 'Create, edit, and manage platform news',
        addNews: 'Add News',
        editNews: 'Edit News',
        deleteNews: 'Delete News',
        newsTitle: 'Title',
        newsDescription: 'Description',
        newsMedia: 'Media (Optional)',
        newsImage: 'Image',
        newsVideo: 'Video',
        uploadMedia: 'Click to upload image or video',
        uploadMediaDesc: 'PNG, JPG, MP4 (Max 50MB)',
        updateNews: 'Update News',
        newsAdded: 'News added successfully!',
        newsUpdated: 'News updated successfully!',
        newsDeleted: 'News deleted successfully',
        deleteNewsConfirm: 'Are you sure you want to delete this news?',
        noNewsYet: 'No news yet. Click "Add News" to create your first news item.',
        latestNews: 'Latest News',
        newsSubtitle: 'Stay updated with the latest announcements and platform updates',
        noNewsAvailable: 'No News Yet',
        checkBackLater: 'Check back later for platform updates and announcements',
        lastUpdated: 'Last updated',
        titleRequired: 'Title and description are required!',

        // Telegram
        joinTelegram: 'Join our Telegram Channel',
        scanQrCode: 'Scan QR Code or click the button below',
        goToChannel: 'Go to Channel',

        // Homepage Hero & Sections
        homepageVideoUrl: 'Homepage Hero Video URL',
        homepageVideoDesc: 'YouTube URL only. Autoplay and sound apply to the new video.',
        platformHighlights: 'Platform Highlights',
        professionalTradingEducation: 'Professional Trading Education',
        professionalTradingEducationDesc: 'Structured curriculum designed by experts for serious traders.',
        stepByStepLearning: 'Step-by-Step Learning Levels',
        stepByStepLearningDesc: 'Clear milestones and progress tracking at every stage.',
        beginnerToProPath: 'Beginner to Professional Path',
        beginnerToProPathDesc: 'Grow from basics to advanced strategies with a clear roadmap.',
        learningSystemOverview: 'Learning System Overview',
        learningProgression: 'Your path from beginner to professional',
        beginnerLevel: 'Beginner',
        intermediateLevel: 'Intermediate',
        professionalLevel: 'Professional',
        whyChoosePlatform: 'Why Choose This Platform',
        structuredCourses: 'Structured Courses',
        structuredCoursesDesc: 'Organized modules and clear learning paths.',
        premiumContentDesc: 'Exclusive strategies and in-depth analysis.',
        realMarketKnowledge: 'Real Market Knowledge',
        realMarketKnowledgeDesc: 'Practical skills backed by live market experience.',
        videoUnavailable: 'Video unavailable',
        watchOnYouTube: 'Watch on YouTube',

        // Course categories
        categoryTradingPlatform: 'Trading Platform',
        categoryNewsCourses: 'News Courses',
        categoryPaidCourses: 'Paid Courses',
        categoryPraxis: 'Praxis & Training',
        courseCategory: 'Course Category',
        courseCategoryRequired: 'Please select a course category.',
        courseLevelNewsOnly: 'Levels (Beginner / Intermediate / Professional) apply to Trading Platform only. News Courses have no level.',
        noCoursesInCategory: 'No courses in this category yet.',
        filterByCategory: 'Filter by category',
        allCategories: 'All Categories',
        coursesPerCategory: 'Courses per category',
        categoryDisplayControl: 'Course category display',
        categoryDisplayControlDesc: 'Enable or disable each category on the Courses page. Changes apply instantly.',
        categoryOrder: 'Category order',
        moveUp: 'Move up',
        moveDown: 'Move down',

        // Homepage redesign — Hero
        heroHeadline: 'All‑in‑One Trading Education Platform',
        heroValueProp: 'From Trading Platform basics to News Courses, Paid Programs, and Praxis & Training — everything is organized for serious traders who want clarity and results.',
        joinCourses: 'Join Courses',
        contactSupport: 'Contact Support',

        // About the Platform
        aboutPlatform: 'Learn in Four Smart Sections',
        aboutPlatformLead: 'Trading Platform • News Courses • Paid Courses • Praxis & Training — a clear system that matches how real traders learn.',
        aboutPoint1: 'Professional trading education designed by experienced analysts.',
        aboutPoint2: 'Structured learning path with free and paid content for every stage.',
        aboutPoint3: 'Praxis & Training focused on real market cases, not just theory.',

        // Signals & Community
        signalsAndCommunity: 'Signals & Community',
        signalsLead: 'Stay connected with live signals and educational content.',
        telegramSignalsChannel: 'Main Signals Channel',
        telegramSignalsDesc: 'Live trading signals and market updates.',
        telegramCoursesChannel: 'Courses & Education',
        telegramCoursesDesc: 'Course updates, lessons, and learning materials.',
        valueLiveSignals: 'Live signals',
        valueEducationalContent: 'Educational content',
        valueCommunityInteraction: 'Community interaction',

        // Contact & Support
        contactAndSupport: 'Contact & Support',
        contactLead: 'We’re here to help.',
        contactSupportDesc: 'Get help with support, subscription inquiries, and premium access.',
        contactTelegramLabel: 'Contact us on Telegram',

        // Why Choose Us (trust cards)
        whyChooseUs: 'Why Choose Us',
        whyTrustedKnowledge: 'Trusted Trading Knowledge',
        whyTrustedKnowledgeDesc: 'Content created by experienced traders and analysts.',
        whyOrganizedLevels: 'Organized Course Levels',
        whyOrganizedLevelsDesc: 'Clear path from beginner to professional.',
        whyPremiumAndFree: 'Premium & Free Content',
        whyPremiumAndFreeDesc: 'Mix of free and premium courses for every goal.',
        whyCommunityDriven: 'Community-Driven Learning',
        whyCommunityDrivenDesc: 'Learn alongside a supportive trading community.',
    },
    ar: {
        // Navbar
        adminDashboard: 'لوحة الإدارة',
        courses: 'الدورات',
        stock: 'سجل التداول',
        logout: 'تسجيل الخروج',
        usersManagement: 'المستخدمين',

        // Login Page
        welcomeBack: 'مرحباً بعودتك',
        signInToAccount: 'سجل الدخول إلى حساب KMT Trade',
        emailAddress: 'البريد الإلكتروني',
        password: 'كلمة المرور',
        secureLogin: 'تسجيل دخول آمن',
        authenticating: 'جارٍ المصادقة...',
        dontHaveAccount: 'ليس لديك حساب؟',
        signUp: 'إنشاء حساب',
        secureTrading: 'منصة تداول آمنة',

        // Stock Journal
        tradingDashboard: 'لوحة التداول',
        stockJournal: 'سجل التداول',
        startingCapital: 'رأس المال المبدئي',
        currentCapital: 'رأس المال الحالي',
        totalProfitLoss: 'إجمالي الربح/الخسارة',
        logNewTrade: 'تسجيل صفقة جديدة',
        enterTradeDetails: 'أدخل تفاصيل الصفقة أدناه',
        date: 'التاريخ',
        assetName: 'اسم الأصل',
        tradeType: 'نوع الصفقة',
        buyLong: 'شراء / طويل',
        sellShort: 'بيع / قصير',
        quantity: 'الكمية',
        entryPrice: 'سعر الدخول',
        exitPrice: 'سعر الخروج',
        strategyTag: 'وسم الاستراتيجية',
        tradeNotes: 'ملاحظات الصفقة',
        addTradeEntry: 'إضافة الصفقة',
        filters: 'تصفية',
        exportData: 'تصدير البيانات',
        totalTrades: 'إجمالي الصفقات',
        winRate: 'نسبة النجاح',
        bestTrade: 'أفضل صفقة',
        worstTrade: 'أسوأ صفقة',
        avgMonthlyReturn: 'متوسط العائد الشهري',
        equityGrowth: 'نمو المحفظة',
        cumulativePerformance: 'الأداء التراكمي بمرور الوقت',
        monthlyPerformance: 'الأداء الشهري',
        profitLossPerMonth: 'نسبة الربح والخسارة لكل شهر',
        tradeHistory: 'سجل الصفقات',
        noTradesLogged: 'لم يتم تسجيل صفقات بعد. ابدأ بإضافة أول صفقة.',
        assetLabel: 'التاريخ / الأصل',
        typeLabel: 'النوع',
        entryExitLabel: 'دخول / خروج',
        qtyLabel: 'الكمية',
        profitLossLabel: 'الربح / الخسارة',
        strategyLabel: 'الاستراتيجية',
        actionsLabel: 'إجراءات',
        confirmDelete: 'حذف الصفقة؟',
        journal: 'سجل الملاحظات',
        confidence: 'مستوى الثقة',
        uploadScreenshots: 'رفع لقطات الشاشة',
        chooseFile: 'اختر ملف',
        noFileChosen: 'لم يتم اختيار ملف',
        clickToUpload: 'انقر للرفع أو اسحب وأفلت',
        imageNote: 'PNG, JPG أو WEBP (الحد الأقصى 2 ميجابايت)',
        copyright: '© 2026 KMT Trade. جميع الحقوق محفوظة.',

        // Signup Page
        createAccount: 'إنشاء حساب',
        joinKMT: 'انضم إلى KMT Trade وابدأ رحلة التداول',
        fullName: 'الاسم الكامل',
        confirmPassword: 'تأكيد كلمة المرور',
        creatingAccount: 'جارٍ إنشاء الحساب...',
        alreadyHaveAccount: 'لديك حساب بالفعل؟',
        signIn: 'تسجيل الدخول',

        // Landing Page
        professionalTrading: 'تعليم التداول الاحترافي - KMT Trade',
        masterMarkets: 'إتقان الأسواق',
        withConfidence: 'بثقة',
        tradingDescription: 'تعليم تداول احترافي مصمم للمستثمرين الجادين. افتح استراتيجيات متميزة وتحليلات مباشرة وإرشاد من الخبراء.',
        startLearning: 'ابدأ التعلم الآن',
        viewCourses: 'عرض الدورات',
        students: 'طالب',
        certifiedMentors: 'مرشدون معتمدون',

        // Courses Page
        tradingCourses: 'الدورات ومسارات التعلم',
        courseDescription: 'استعرض منصة التداول، دورات الأخبار، البرامج المدفوعة، وبراكسيس والتدريب — كلها منظمة في مكان واحد.',
        lessons: 'دروس',
        waitlist: 'قائمة الانتظار',
        startCourse: 'ابدأ الدورة',
        continueCourse: 'متابعة الدورة',
        completed: 'مكتمل',

        // Video Player
        premiumContent: 'محتوى مميز',
        premiumDescription: 'هذا الدرس مخصص لأعضائنا المميزين. افتح الوصول الكامل لترفع مستوى التداول الخاص بك.',
        subscribeToUnlock: 'اشترك للفتح',
        courseContent: 'محتوى الدورة',

        // Admin Dashboard
        adminDashboardTitle: 'لوحة الإدارة',
        totalUsers: 'إجمالي المستخدمين',
        premiumMembers: 'الأعضاء المميزون',
        totalContent: 'إجمالي المحتوى',
        revenue: 'الإيرادات (تقديري)',
        userManagement: 'إدارة المستخدمين',
        manageAccess: 'إدارة حقوق الوصول',
        user: 'المستخدم',
        email: 'البريد الإلكتروني',
        role: 'الدور',
        status: 'الحالة',
        actions: 'الإجراءات',
        admin: 'مدير',
        normal: 'عادي',
        premium: 'مميز',
        activatePremium: 'تفعيل المميز',
        deactivatePremium: 'إلغاء المميز',
        quickAccess: 'الوصول السريع',
        usersDesc: 'إدارة المستخدمين والأدوار والاشتراكات',
        coursesDesc: 'إدارة محتوى الدورة والظهور',
        uploadDesc: 'تحميل دروس فيديو جديدة',
        newsDesc: 'نشر الأخبار والإعلانات',
        settingsDesc: 'تكوين إعدادات المنصة',
        stockJournalDesc: 'سجل التداول الشخصي وتحليلات الأداء',
        goToPage: 'الذهاب للصفحة',

        // Dashboard Stats & Charts
        overview: 'نظرة عامة على النظام',
        userDistribution: 'توزيع المستخدمين',
        revenueTrends: 'اتجاهات الإيرادات',
        contentPerformance: 'أداء المحتوى',
        premiumUsers: 'مستخدمين مميزين',
        freeUsers: 'مستخدمين مجانيين',
        admins: 'مستخدمين إداريين',
        monthlyGrowth: 'النمو الشهري',
        last30Days: 'آخر 30 يوم',
        totalViews: 'إجمالي المشاهدات',
        engagement: 'المشاركة',

        // Admin Sidebar
        courseManagement: 'إدارة الدورات',
        profile: 'الملف الشخصي',

        // Course Management
        addNewCourse: 'إضافة دورة جديدة',
        courseTitle: 'عنوان الدورة',
        adminCourseDescription: 'وصف الدورة',
        courseThumbnail: 'رابط الصورة المصغرة',
        courseLevel: 'مستوى الدورة',
        courseType: 'نوع الدورة',
        public: 'عام',
        premiumOnly: 'للمميزين فقط',
        beginner: 'مبتدئ',
        intermediate: 'متوسط',
        professional: 'احترافي',
        yourCurrentLevel: 'مستواك الحالي',
        levelProgress: 'تقدم المستوى',
        levelCompleteDesc: 'تم اكتمال المستوى! تم فتح المستوى التالي.',
        completeVideosToUnlock: 'أكمل كل الفيديوهات لفتح المستوى التالي.',
        uploadCourse: 'رفع دورة',
        editCourse: 'تعديل الدورة',
        deleteCourse: 'حذف الدورة',
        hideCourse: 'إخفاء الدورة',
        showCourse: 'إظهار الدورة',
        courseStats: 'إحصائيات الدورة',
        premiumViews: 'مشاهدات المميزين',
        cancel: 'إلغاء',
        save: 'حفظ',
        delete: 'حذف',
        confirm: 'تأكيد',
        edit: 'تعديل',

        // User Management
        searchUsers: 'البحث عن مستخدمين...',
        filterByStatus: 'تصفية حسب الحالة',
        allUsers: 'جميع المستخدمين',
        activeUsers: 'المستخدمين النشطين',
        inactiveUsers: 'المستخدمين غير النشطين',
        userId: 'معرف المستخدم',
        accountStatus: 'حالة الحساب',
        subscriptionStatus: 'الاشتراك',
        active: 'نشط',
        inactive: 'غير نشط',
        activateAccount: 'تفعيل الحساب',
        deactivateAccount: 'تعطيل الحساب',
        deleteAccount: 'حذف الحساب',
        deleteUserConfirm: 'هل أنت متأكد أنك تريد حذف هذا المستخدم؟',
        deleteUserWarning: 'هذا الإجراء لا يمكن التراجع عنه.',

        // Admin Profile
        adminProfile: 'ملف المسؤول',
        profileImage: 'صورة الملف الشخصي',
        changeImage: 'تغيير الصورة',
        adminName: 'الاسم',
        adminEmail: 'البريد الإلكتروني',
        editProfile: 'تعديل الملف الشخصي',
        saveChanges: 'حفظ التغييرات',
        profileUpdated: 'تم تحديث الملف الشخصي بنجاح',

        // Messages
        courseAdded: 'تمت إضافة الدورة بنجاح',
        courseUpdated: 'تم تحديث الدورة بنجاح',
        courseDeleted: 'تم حذف الدورة بنجاح',
        userDeleted: 'تم حذف المستخدم بنجاح',
        userActivated: 'تم تفعيل المستخدم بنجاح',
        userDeactivated: 'تم تعطيل المستخدم بنجاح',
        settings: 'الإعدادات',

        // Upload Course Page (Arabic)
        uploadCoursePageTitle: 'رفع فيديو الدورة',
        courseDetails: 'تفاصيل الدورة',
        videoDetails: 'تفاصيل الفيديو',
        accessSettings: 'إعدادات الوصول',
        videoTitle: 'عنوان الفيديو',
        videoDescription: 'وصف الفيديو',
        dragDropVideo: 'اسحب وأفلت الفيديو هنا',
        orBrowse: 'أو تصفح للرفع',
        videoDuration: 'المدة (دقيقة:ثانية)',
        videoType: 'نوع الفيديو',
        free: 'مجاني',
        uploading: 'جارٍ الرفع...',
        uploadSuccess: 'تم رفع الفيديو بنجاح!',
        uploadError: 'خطأ في رفع الفيديو',
        selectThumbnail: 'اختر صورة مصغرة',
        thumbnailPreview: 'معاينة الصورة المصغرة',
        fileSelected: 'تم اختيار الملف:',
        removeFile: 'إزالة',

        // Users Page Translates
        manageUsersDesc: 'إدارة مستخدمي المنصة والاشتراكات',
        joined: 'تاريخ الانضمام',
        noUsersFound: 'لم يتم العثور على مستخدمين يطابقون',
        removePremium: 'إلغاء المميز',
        makePremium: 'ترقية لمميز',
        freePlan: 'خطة مجانية',
        premiumPlan: 'خطة مميزة',
        learningLevel: 'مستوى التعلم',
        progress: 'التقدم',

        // Courses Settings Page Translates
        coursesSettingsTitle: 'إعدادات الدورات',
        manageCoursesDesc: 'إدارة وتنظيم محتوى الدورات التدريبية',
        noImage: 'لا توجد صورة',
        startUploading: 'لا توجد دورات متاحة. ابدأ برفع واحدة.',
        published: 'منشور',
        hidden: 'مخفي',
        deleteCourseConfirm: 'هل أنت متأكد أنك تريد حذف هذه الدورة؟',

        // Settings Page Translates
        platformSettings: 'إعدادات المنصة',
        general: 'عام',
        platformName: 'اسم المنصة',
        platformNameDesc: 'سيظهر هذا الاسم في عنوان الصفحة والرسائل.',
        themePreference: 'تفضيلات المظهر',
        current: 'الحالي',
        switchTheme: 'تبديل المظهر',
        systemLanguage: 'لغة النظام',
        switchLanguage: 'تبديل اللغة',
        accessControl: 'التحكم في الوصول',
        adminOnly: 'للمسؤولين فقط',
        maintenanceMode: 'وضع الصيانة',
        maintenanceModeDesc: 'تعطيل الوصول لجميع المستخدمين غير المسؤولين',
        allowSignups: 'السماح بالتسجيلات الجديدة',
        allowSignupsDesc: 'تمكين أو تعطيل تسجيل المستخدمين الجدد',
        lightMode: 'وضع فاتح',
        darkMode: 'وضع داكن',
        english: 'إنجليزي',
        arabic: 'عربي',

        // News Page Translates
        news: 'الأخبار',
        newsManagement: 'إدارة الأخبار',
        newsManagementDesc: 'إنشاء وتحرير وإدارة أخبار المنصة',
        addNews: 'إضافة خبر',
        editNews: 'تعديل الخبر',
        deleteNews: 'حذف الخبر',
        newsTitle: 'العنوان',
        newsDescription: 'الوصف',
        newsMedia: 'وسائط (اختياري)',
        newsImage: 'صورة',
        newsVideo: 'فيديو',
        uploadMedia: 'انقر لتحميل صورة أو فيديو',
        uploadMediaDesc: 'PNG، JPG، MP4 (الحد الأقصى 50 ميجابايت)',
        updateNews: 'تحديث الخبر',
        newsAdded: 'تمت إضافة الخبر بنجاح!',
        newsUpdated: 'تم تحديث الخبر بنجاح!',
        newsDeleted: 'تم حذف الخبر بنجاح',
        deleteNewsConfirm: 'هل أنت متأكد أنك تريد حذف هذا الخبر؟',
        noNewsYet: 'لا توجد أخبار حتى الآن. انقر على "إضافة خبر" لإنشاء أول خبر.',
        latestNews: 'آخر الأخبار',
        newsSubtitle: 'ابق على اطلاع بآخر الإعلانات وتحديثات المنصة',
        noNewsAvailable: 'لا توجد أخبار حتى الآن',
        checkBackLater: 'تحقق مرة أخرى لاحقًا للحصول على تحديثات وإعلانات المنصة',
        lastUpdated: 'آخر تحديث',
        titleRequired: 'العنوان والوصف مطلوبان!',

        // Telegram
        joinTelegram: 'انضم إلى قناة التليجرام',
        scanQrCode: 'امسح الرمز أو انقر على الزر أدناه',
        goToChannel: 'الذهاب للقناة',

        // Homepage Hero & Sections (Arabic)
        homepageVideoUrl: 'رابط فيديو الصفحة الرئيسية',
        homepageVideoDesc: 'رابط يوتيوب فقط. التشغيل التلقائي والصوت ينطبقان على الفيديو الجديد.',
        platformHighlights: 'أبرز المنصة',
        professionalTradingEducation: 'تعليم تداول احترافي',
        professionalTradingEducationDesc: 'منهج منظم من خبراء للمتداولين الجادين.',
        stepByStepLearning: 'مستويات تعلم خطوة بخطوة',
        stepByStepLearningDesc: 'معالم واضحة وتتبع التقدم في كل مرحلة.',
        beginnerToProPath: 'من المبتدئ إلى المحترف',
        beginnerToProPathDesc: 'تطور من الأساسيات إلى الاستراتيجيات المتقدمة بخطة واضحة.',
        learningSystemOverview: 'نظرة على نظام التعلم',
        learningProgression: 'مسارك من المبتدئ إلى المحترف',
        beginnerLevel: 'مبتدئ',
        intermediateLevel: 'متوسط',
        professionalLevel: 'احترافي',
        whyChoosePlatform: 'لماذا هذه المنصة',
        structuredCourses: 'دورات منظمة',
        structuredCoursesDesc: 'وحدات منظمة ومسارات تعلم واضحة.',
        premiumContentDesc: 'استراتيجيات حصرية وتحليل معمق.',
        realMarketKnowledge: 'معرفة السوق الحقيقية',
        realMarketKnowledgeDesc: 'مهارات عملية مدعومة بتجربة السوق المباشرة.',
        videoUnavailable: 'الفيديو غير متاح',
        watchOnYouTube: 'شاهد على يوتيوب',

        // Course categories (Arabic)
        categoryTradingPlatform: 'منصة التداول',
        categoryNewsCourses: 'دورات الأخبار',
        categoryPaidCourses: 'دورات مدفوعة',
        categoryPraxis: 'براكسيس وتدريب',
        courseCategory: 'فئة الدورة',
        courseCategoryRequired: 'يرجى اختيار فئة الدورة.',
        courseLevelNewsOnly: 'المستويات (مبتدئ / متوسط / احترافي) لمنصة التداول فقط. دورات الأخبار لا تحتوي على مستوى.',
        noCoursesInCategory: 'لا توجد دورات في هذه الفئة بعد.',
        filterByCategory: 'تصفية حسب الفئة',
        allCategories: 'جميع الفئات',
        coursesPerCategory: 'الدورات حسب الفئة',
        categoryDisplayControl: 'عرض فئات الدورات',
        categoryDisplayControlDesc: 'تفعيل أو إخفاء كل فئة في صفحة الدورات. التغييرات فورية.',
        categoryOrder: 'ترتيب الفئات',
        moveUp: 'تحريك لأعلى',
        moveDown: 'تحريك لأسفل',

        // Homepage redesign — Hero (Arabic)
        heroHeadline: 'منصة تعليم تداول متكاملة',
        heroValueProp: 'من أساسيات منصة التداول إلى دورات الأخبار والبرامج المدفوعة وبراكسيس والتدريب — كل شيء منظم لمتداولين جادين يبحثون عن وضوح ونتائج.',
        joinCourses: 'انضم للدورات',
        contactSupport: 'تواصل مع الدعم',

        // About the Platform (Arabic)
        aboutPlatform: 'تعلم عبر أربع مسارات رئيسية',
        aboutPlatformLead: 'منصة التداول • دورات الأخبار • الدورات المدفوعة • براكسيس والتدريب — نظام واضح يناسب طريقة تعلم المتداول الحقيقي.',
        aboutPoint1: 'تعليم تداول احترافي من محللين ذوي خبرة.',
        aboutPoint2: 'مسار تعلم منظم يجمع بين محتوى مجاني ومدفوع لكل مرحلة.',
        aboutPoint3: 'قسم براكسيس وتدريب يركز على حالات حقيقية من السوق وليس النظري فقط.',

        // Signals & Community (Arabic)
        signalsAndCommunity: 'الإشارات والمجتمع',
        signalsLead: 'ابق على تواصل مع الإشارات المباشرة والمحتوى التعليمي.',
        telegramSignalsChannel: 'قناة الإشارات الرئيسية',
        telegramSignalsDesc: 'إشارات تداول مباشرة وتحديثات السوق.',
        telegramCoursesChannel: 'الدورات والتعليم',
        telegramCoursesDesc: 'تحديثات الدورات والدروس والمواد التعليمية.',
        valueLiveSignals: 'إشارات مباشرة',
        valueEducationalContent: 'محتوى تعليمي',
        valueCommunityInteraction: 'تفاعل مجتمعي',

        // Contact & Support (Arabic)
        contactAndSupport: 'التواصل والدعم',
        contactLead: 'نحن هنا لمساعدتك.',
        contactSupportDesc: 'احصل على مساعدة في الدعم واستفسارات الاشتراك والوصول المميز.',
        contactTelegramLabel: 'تواصل معنا على تليجرام',

        // Why Choose Us (Arabic)
        whyChooseUs: 'لماذا نحن',
        whyTrustedKnowledge: 'معرفة تداول موثوقة',
        whyTrustedKnowledgeDesc: 'محتوى من متداولين ومحللين ذوي خبرة.',
        whyOrganizedLevels: 'مستويات دورات منظمة',
        whyOrganizedLevelsDesc: 'مسار واضح من المبتدئ إلى الاحترافي.',
        whyPremiumAndFree: 'محتوى مميز ومجاني',
        whyPremiumAndFreeDesc: 'مزيج من دورات مجانية ومميزة لكل هدف.',
        whyCommunityDriven: 'تعلم قائم على المجتمع',
        whyCommunityDrivenDesc: 'تعلم ضمن مجتمع تداول داعم.',
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('en');

    useEffect(() => {
        const savedLang = localStorage.getItem('kmt_language') || 'en';
        setLanguage(savedLang);
        applyDirection(savedLang);
    }, []);

    const applyDirection = (lang) => {
        document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
        document.documentElement.lang = lang;
    };

    const toggleLanguage = () => {
        const newLang = language === 'en' ? 'ar' : 'en';
        setLanguage(newLang);
        localStorage.setItem('kmt_language', newLang);
        applyDirection(newLang);
    };

    const t = (key) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
